# Form implementation generated from reading ui file 'app_apoyo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 894)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("Qwidget{\n"
"background-image: url(:/fondo/imagenes/fondo.jpeg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("font: 18pt \"Courier New\";\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(146, 218, 205, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 48pt \"Courier New\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_9.setSpacing(25)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_2 = QtWidgets.QFrame(parent=self.page_5)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 550))
        self.frame_2.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(92, 130, 255);\n"
"border-radius: 50%;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(92, 130, 255);\n"
"font-size:25px;\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 196, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid  rgb(16, 72, 255)   ;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagenes/fisica.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(374, 374))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("font: 57 28pt \"Courier Std\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_9.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.page_5)
        self.frame_3.setMinimumSize(QtCore.QSize(389, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 550))
        self.frame_3.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(255, 201, 251);\n"
"border-radius: 50%;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 201, 251);\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 222, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid  rgb(233, 143, 255)   ;\n"
"}")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imagenes/psicologica_preview_rev_1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(374, 374))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Courier Std")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 57 28pt \"Courier Std\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_4.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.btn_inicio1 = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_inicio1.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio1.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imagenes/casa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_inicio1.setIcon(icon2)
        self.btn_inicio1.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio1.setObjectName("btn_inicio1")
        self.horizontalLayout_11.addWidget(self.btn_inicio1)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_12.setSpacing(25)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_5 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 550))
        self.frame_5.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 50;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 170, 0);\n"
"font-size:25px;\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 212, 55);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid  rgb(255, 128, 0);\n"
"}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imagenes/malestar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(374, 374))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setStyleSheet("font: 57 28pt \"Courier Std\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.horizontalLayout_12.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 550))
        self.frame_6.setStyleSheet("background-color: rgb(20, 206, 73);\n"
"font: 57 20pt \"Courier Std\";\n"
"border-radius: 50;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(20, 206, 73);\n"
"font-size:25px;\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(147, 255, 6);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid rgb(31, 170, 0);\n"
"}")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imagenes/ejercicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(370, 353))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_9.addWidget(self.pushButton_4)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setStyleSheet("font: 57 28pt \"Courier Std\";")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout_12.addWidget(self.frame_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_13 = QtWidgets.QFrame(parent=self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_13.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_14.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.btn_inicio_2 = QtWidgets.QPushButton(parent=self.frame_13)
        self.btn_inicio_2.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio_2.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio_2.setText("")
        self.btn_inicio_2.setIcon(icon2)
        self.btn_inicio_2.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio_2.setObjectName("btn_inicio_2")
        self.horizontalLayout_3.addWidget(self.btn_inicio_2)
        self.verticalLayout_19.addWidget(self.frame_13)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout_20.setSpacing(25)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_14 = QtWidgets.QFrame(parent=self.page_7)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 550))
        self.frame_14.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(172, 103, 255);\n"
"border-radius: 50;\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_14)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: rgb(172, 103, 255);\n"
"font-size:25px;\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(186, 130, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid  rgb(145, 35, 255);\n"
"}")
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("imagenes/meditacion.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(374, 374))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_21.addWidget(self.pushButton_11)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 550))
        self.label_15.setStyleSheet("font: 57 28pt \"Courier Std\";")
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.horizontalLayout_20.addWidget(self.frame_14)
        self.widget = QtWidgets.QWidget(parent=self.page_7)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 550))
        self.widget.setStyleSheet("font: 57 28pt \"Courier Std\";\n"
"background-color: rgb(193, 193, 193);\n"
"border-radius: 50;\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(193, 193, 193);\n"
"font-size:25px;\n"
"\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"QPushButton:pressed{\n"
"border: 2px solid  rgb(173, 173, 173);\n"
"}")
        self.pushButton_5.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("imagenes/estres.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon6)
        self.pushButton_5.setIconSize(QtCore.QSize(374, 374))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_22.addWidget(self.pushButton_5)
        self.label_16 = QtWidgets.QLabel(parent=self.widget)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 550))
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_22.addWidget(self.label_16)
        self.horizontalLayout_20.addWidget(self.widget)
        self.verticalLayout_19.addLayout(self.horizontalLayout_20)
        self.stackedWidget.addWidget(self.page_7)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_7 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_7.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_7.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.btn_inicio3 = QtWidgets.QPushButton(parent=self.frame_7)
        self.btn_inicio3.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio3.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio3.setText("")
        self.btn_inicio3.setIcon(icon2)
        self.btn_inicio3.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio3.setObjectName("btn_inicio3")
        self.horizontalLayout_4.addWidget(self.btn_inicio3)
        self.verticalLayout.addWidget(self.frame_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_8 = QtWidgets.QFrame(parent=self.page)
        self.frame_8.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.frame_8.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(450, -40, 531, 681))
        self.label_8.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("imagenes/cuerpo.png"))
        self.label_8.setObjectName("label_8")
        self.Cabeza = QtWidgets.QPushButton(parent=self.frame_8)
        self.Cabeza.setGeometry(QtCore.QRect(640, 0, 41, 41))
        self.Cabeza.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Cabeza.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Cabeza.setText("")
        self.Cabeza.setObjectName("Cabeza")
        self.Garganta = QtWidgets.QPushButton(parent=self.frame_8)
        self.Garganta.setGeometry(QtCore.QRect(640, 80, 41, 41))
        self.Garganta.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Garganta.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Garganta.setText("")
        self.Garganta.setObjectName("Garganta")
        self.Pecho = QtWidgets.QPushButton(parent=self.frame_8)
        self.Pecho.setGeometry(QtCore.QRect(640, 150, 41, 41))
        self.Pecho.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Pecho.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Pecho.setText("")
        self.Pecho.setObjectName("Pecho")
        self.Estomago = QtWidgets.QPushButton(parent=self.frame_8)
        self.Estomago.setGeometry(QtCore.QRect(640, 230, 41, 41))
        self.Estomago.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Estomago.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Estomago.setText("")
        self.Estomago.setObjectName("Estomago")
        self.Hombro = QtWidgets.QPushButton(parent=self.frame_8)
        self.Hombro.setGeometry(QtCore.QRect(710, 110, 41, 41))
        self.Hombro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Hombro.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Hombro.setText("")
        self.Hombro.setObjectName("Hombro")
        self.Brazo = QtWidgets.QPushButton(parent=self.frame_8)
        self.Brazo.setGeometry(QtCore.QRect(550, 230, 41, 41))
        self.Brazo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Brazo.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Brazo.setText("")
        self.Brazo.setObjectName("Brazo")
        self.Pierna = QtWidgets.QPushButton(parent=self.frame_8)
        self.Pierna.setGeometry(QtCore.QRect(680, 380, 41, 41))
        self.Pierna.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Pierna.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Pierna.setText("")
        self.Pierna.setObjectName("Pierna")
        self.Pie = QtWidgets.QPushButton(parent=self.frame_8)
        self.Pie.setGeometry(QtCore.QRect(610, 550, 41, 41))
        self.Pie.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Pie.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.Pie.setText("")
        self.Pie.setObjectName("Pie")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_8)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(290, 280, 158, 152))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fuerte = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.fuerte.setStyleSheet("font: 20pt \"Courier New\";\n"
"background-color: rgba(0, 0,0, 0);")
        self.fuerte.setObjectName("fuerte")
        self.verticalLayout_3.addWidget(self.fuerte)
        self.medio = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.medio.setStyleSheet("font: 20pt \"Courier New\";\n"
"background-color: rgba(0, 0,0, 0);")
        self.medio.setObjectName("medio")
        self.verticalLayout_3.addWidget(self.medio)
        self.leve = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget_2)
        self.leve.setStyleSheet("font: 20pt \"Courier New\";\n"
"background-color: rgba(0, 0,0, 0);")
        self.leve.setObjectName("leve")
        self.verticalLayout_3.addWidget(self.leve)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_3.addWidget(self.pushButton_15)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_9.setGeometry(QtCore.QRect(250, 170, 251, 41))
        self.label_9.setStyleSheet("font: 20pt \"Courier New\";\n"
"background-color: rgba(0, 0,0, 0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_10.setGeometry(QtCore.QRect(250, 220, 251, 41))
        self.label_10.setStyleSheet("font: 20pt \"Courier New\";\n"
"background-color: rgb(202, 202, 202);\n"
"border-radius: 20px;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.frame_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_9 = QtWidgets.QFrame(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_11.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.btn_inicio4 = QtWidgets.QPushButton(parent=self.frame_9)
        self.btn_inicio4.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio4.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio4.setText("")
        self.btn_inicio4.setIcon(icon2)
        self.btn_inicio4.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio4.setObjectName("btn_inicio4")
        self.horizontalLayout_13.addWidget(self.btn_inicio4)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ganar_musculo = QtWidgets.QRadioButton(parent=self.page_2)
        self.ganar_musculo.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.ganar_musculo.setObjectName("ganar_musculo")
        self.horizontalLayout_5.addWidget(self.ganar_musculo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.perder_grasa = QtWidgets.QRadioButton(parent=self.page_2)
        self.perder_grasa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.perder_grasa.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.perder_grasa.setObjectName("perder_grasa")
        self.horizontalLayout_5.addWidget(self.perder_grasa)
        self.balancear = QtWidgets.QRadioButton(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balancear.sizePolicy().hasHeightForWidth())
        self.balancear.setSizePolicy(sizePolicy)
        self.balancear.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.balancear.setObjectName("balancear")
        self.horizontalLayout_5.addWidget(self.balancear)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        self.label_12 = QtWidgets.QLabel(parent=self.page_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_12.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 20pt \"Courier New\";")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_16.setMaximumSize(QtCore.QSize(220, 60))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border-radius: 20%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_7.addWidget(self.pushButton_16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(parent=self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_13.setMinimumSize(QtCore.QSize(0, 80))
        self.label_13.setStyleSheet("background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";\n"
"color:white;")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.btn_inicio5 = QtWidgets.QPushButton(parent=self.frame_10)
        self.btn_inicio5.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio5.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio5.setText("")
        self.btn_inicio5.setIcon(icon2)
        self.btn_inicio5.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio5.setObjectName("btn_inicio5")
        self.horizontalLayout_14.addWidget(self.btn_inicio5)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.page_3)
        self.scrollArea.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 82, 1284))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_13.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_13.setSpacing(20)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_17 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_17.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(92, 130, 255);\n"
"border-radius: 50%;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_21.setGeometry(QtCore.QRect(20, 30, 811, 101))
        self.label_21.setStyleSheet("color:white;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_22.setGeometry(QtCore.QRect(340, 120, 211, 151))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("imagenes/depre.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.depresion = QtWidgets.QPushButton(parent=self.frame_17)
        self.depresion.setGeometry(QtCore.QRect(580, 160, 61, 61))
        self.depresion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.depresion.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.depresion.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("imagenes/mas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.depresion.setIcon(icon7)
        self.depresion.setIconSize(QtCore.QSize(50, 50))
        self.depresion.setObjectName("depresion")
        self.verticalLayout_13.addWidget(self.frame_17)
        self.frame_16 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_16.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(172, 103, 255);\n"
"border-radius: 50%;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_25.setGeometry(QtCore.QRect(30, 30, 811, 101))
        self.label_25.setStyleSheet("color:white;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_26.setGeometry(QtCore.QRect(380, 150, 121, 111))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("imagenes/bipo.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.bipolaridad = QtWidgets.QPushButton(parent=self.frame_16)
        self.bipolaridad.setGeometry(QtCore.QRect(580, 160, 61, 61))
        self.bipolaridad.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.bipolaridad.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.bipolaridad.setText("")
        self.bipolaridad.setIcon(icon7)
        self.bipolaridad.setIconSize(QtCore.QSize(50, 50))
        self.bipolaridad.setObjectName("bipolaridad")
        self.verticalLayout_13.addWidget(self.frame_16)
        self.frame_15 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_15.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(20, 206, 73);\n"
"border-radius: 50%;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 811, 101))
        self.label_23.setStyleSheet("color:white;")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_24.setGeometry(QtCore.QRect(340, 120, 211, 171))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("imagenes/ansiedad.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.ansiedad = QtWidgets.QPushButton(parent=self.frame_15)
        self.ansiedad.setGeometry(QtCore.QRect(580, 160, 61, 61))
        self.ansiedad.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.ansiedad.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.ansiedad.setText("")
        self.ansiedad.setIcon(icon7)
        self.ansiedad.setIconSize(QtCore.QSize(50, 50))
        self.ansiedad.setObjectName("ansiedad")
        self.verticalLayout_13.addWidget(self.frame_15)
        self.frame_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_12.setStyleSheet("font: 57 20pt \"Courier Std\";\n"
"background-color: rgb(255, 170, 0);\n"
"border-radius: 50%;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_20.setGeometry(QtCore.QRect(340, 120, 211, 151))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("imagenes/tdah.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.TDAH = QtWidgets.QPushButton(parent=self.frame_12)
        self.TDAH.setGeometry(QtCore.QRect(580, 160, 61, 61))
        self.TDAH.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.TDAH.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(255, 0, 0);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.TDAH.setText("")
        self.TDAH.setIcon(icon7)
        self.TDAH.setIconSize(QtCore.QSize(50, 50))
        self.TDAH.setObjectName("TDAH")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_19.setGeometry(QtCore.QRect(30, 20, 811, 101))
        self.label_19.setStyleSheet("color:white;")
        self.label_19.setObjectName("label_19")
        self.verticalLayout_13.addWidget(self.frame_12)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_12.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_3)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_11 = QtWidgets.QFrame(parent=self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_11.setStyleSheet("background-color: rgba(0, 0,0, 0);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_18.setStyleSheet("color:white;\n"
"background-color: rgb(112, 169, 255);\n"
"border-radius: 40px;\n"
"font: 30pt \"Courier New\";")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_15.addWidget(self.label_18)
        self.btn_inicio6 = QtWidgets.QPushButton(parent=self.frame_11)
        self.btn_inicio6.setMaximumSize(QtCore.QSize(60, 60))
        self.btn_inicio6.setStyleSheet("QPushButton{\n"
"border-radius: 30%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(221, 221, 221);\n"
"}\n"
"")
        self.btn_inicio6.setText("")
        self.btn_inicio6.setIcon(icon2)
        self.btn_inicio6.setIconSize(QtCore.QSize(50, 50))
        self.btn_inicio6.setObjectName("btn_inicio6")
        self.horizontalLayout_15.addWidget(self.btn_inicio6)
        self.verticalLayout_15.addWidget(self.frame_11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_play = QtWidgets.QPushButton(parent=self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setMinimumSize(QtCore.QSize(300, 300))
        self.btn_play.setMaximumSize(QtCore.QSize(300, 300))
        self.btn_play.setStyleSheet("QPushButton{\n"
"border-radius: 150%;\n"
"background-color: rgb(112, 169, 255);\n"
"color:white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(58, 196, 255);\n"
"}")
        self.btn_play.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("imagenes/play2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_play.setIcon(icon8)
        self.btn_play.setIconSize(QtCore.QSize(300, 300))
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_8.addWidget(self.btn_play)
        self.verticalLayout_15.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.page_8)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "FitEase"))
        self.label_2.setText(_translate("MainWindow", "Salud Física"))
        self.label_5.setText(_translate("MainWindow", "Salud Psicológica"))
        self.label_3.setText(_translate("MainWindow", "Ayuda en línea con:"))
        self.label_4.setText(_translate("MainWindow", "Molestias o dolor"))
        self.label_6.setText(_translate("MainWindow", "Dieta y ejercicio"))
        self.label_14.setText(_translate("MainWindow", "Ayuda  con:"))
        self.label_15.setText(_translate("MainWindow", "Meditación"))
        self.label_16.setText(_translate("MainWindow", "Padecimientos"))
        self.label_7.setText(_translate("MainWindow", "Selecciona la zona de malestar:"))
        self.fuerte.setText(_translate("MainWindow", "Fuerte"))
        self.medio.setText(_translate("MainWindow", "Medio"))
        self.leve.setText(_translate("MainWindow", "Leve"))
        self.pushButton_15.setText(_translate("MainWindow", "Buscar"))
        self.label_9.setText(_translate("MainWindow", "Zona del dolor:"))
        self.label_11.setText(_translate("MainWindow", "Objetivo de la dieta:"))
        self.ganar_musculo.setText(_translate("MainWindow", "Ganar músculo"))
        self.perder_grasa.setText(_translate("MainWindow", "Perder grasa"))
        self.balancear.setText(_translate("MainWindow", "Balancear nutrientes"))
        self.label_12.setText(_translate("MainWindow", "Plan de recomendaciones de dieta y ejercicio recomendado:"))
        self.pushButton_16.setText(_translate("MainWindow", "Descargar plan"))
        self.label_13.setText(_translate("MainWindow", "Padecimientos comunes:"))
        self.label_21.setText(_translate("MainWindow", "Depresión: Caracterizado por bajo estado\n"
"de ánimo y sentimientos de tristeza..."))
        self.label_25.setText(_translate("MainWindow", "Bipolaridad:  Altibajos emocionales,\n"
"que van desde trastornos de depresión\n"
"hasta episodios maníacos."))
        self.label_23.setText(_translate("MainWindow", "Ansiedad: Preocupación y miedo intensos,\n"
"excesivos y continuos ante situaciones\n"
"cotidianas..."))
        self.label_19.setText(_translate("MainWindow", "TDAH: Puede ocasionar baja autoestima,\n"
"problemas en las relaciones, en la escuela\n"
"o el trabajo..."))
        self.label_18.setText(_translate("MainWindow", "Medita con el siguiente audio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
